apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: divyansht85/sample-app
        name: sample-app
        ports:
        - containerPort: 80
        resources: {}
      imagePullSecrets:
      - name: regcred
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: sample-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app
  type: LoadBalancer
status:
  loadBalancer: {}
